### PR TITLE
Fix browser support table layout

### PR DESCRIPTION
**Pull request by soul-wish**
Just small fix for support table ;)

@jh3y

### CODE REVIEW

**Review by jh3y — APPROVED** [review]
Hey @soul-wish, good spot! 😄 

Thanks for contributing 👍 

Not sure how I let that slip. I went through the history and took a look for that file. Is it possible that the `markdown` format changed?

**Comment by soul-wish** [comment]
You are welcome! 😉

> Is it possible that the markdown format changed?

Not sure, really.. It seems like there was one redundant column and I just removed it 😎

**Comment by jh3y** [comment]
Strange 😕  Verifying with the `history` I only added that table once to solve #4 and it's unlikely that I would've committed it without checking it rendered properly :joy:

Maybe the rendering has slightly changed in an update and it somehow just worked previously 😄 

Main thing is, it works now 🎉  so thanks again!

@jh3y

**Comment by soul-wish** [comment]
Yeah, I see.. README.md file has this redundant column in the [original commit](https://github.com/jh3y/driveway/commit/2bfb75bd43d093000fe7805fb1ea14f60ec1aea6). It seems like you are right and Github team fixed markdown table syntax somehow. Anyway, keep up the good work on this project 👍

**Pull request merged**
